package CAMod;

import java.awt.Dimension;
import java.awt.Point;

import javafx.application.Application;
import javafx.stage.Stage;
import model.CAmodeling.TwoDimCellSpace;
import view.modeling.ViewableComponent;
import view.modeling.ViewableComponentUtil;

public class ForestOnFire extends TwoDimCellSpace {

	public ForestOnFire() {
		this(20, 20);
	}

	public ForestOnFire(int xDim, int yDim) {
		super("forest", xDim, yDim);
		this.numCells = xDim * yDim;
		for (int i = 0; i < xDimCellspace; i++) {
			for (int j = 0; j < yDimCellspace; j++) {
				Tree tree = new Tree(i, j);
				addCell(tree);
			}
		}

		// Do the couplings

		doNeighborToNeighborCoupling();

	}

	/**
	 * Automatically generated by the SimView program. Do not edit this
	 * manually, as such changes will get overwritten.
	 */
	public void layoutForSimView() {
		preferredSize = new Dimension(800, 700);
		((ViewableComponent) withName("Cell_key = 1 ,value = 3")).setPreferredLocation(new Point(-45, 541));
		((ViewableComponent) withName("Cell_key = 0 ,value = 3")).setPreferredLocation(new Point(-21, 373));
		((ViewableComponent) withName("Cell_key = 1 ,value = 1")).setPreferredLocation(new Point(-64, 198));
		((ViewableComponent) withName("Cell_key = 2 ,value = 2")).setPreferredLocation(new Point(169, 549));
		((ViewableComponent) withName("Cell_key = 1 ,value = 2")).setPreferredLocation(new Point(360, 552));
		((ViewableComponent) withName("Cell_key = 0 ,value = 0")).setPreferredLocation(new Point(203, 378));
		((ViewableComponent) withName("Cell_key = 2 ,value = 0")).setPreferredLocation(new Point(407, 24));
		((ViewableComponent) withName("Cell_key = 2 ,value = 3")).setPreferredLocation(new Point(103, 207));
		((ViewableComponent) withName("Cell_key = 1 ,value = 0")).setPreferredLocation(new Point(482, 213));
		((ViewableComponent) withName("Cell_key = 2 ,value = 1")).setPreferredLocation(new Point(406, 39));
		((ViewableComponent) withName("Cell_key = 3 ,value = 3")).setPreferredLocation(new Point(414, 371));
		((ViewableComponent) withName("Cell_key = 0 ,value = 1")).setPreferredLocation(new Point(179, 38));
		((ViewableComponent) withName("Cell_key = 3 ,value = 2")).setPreferredLocation(new Point(-89, 29));
		((ViewableComponent) withName("Cell_key = 3 ,value = 0")).setPreferredLocation(new Point(516, 555));
		((ViewableComponent) withName("Cell_key = 0 ,value = 2")).setPreferredLocation(new Point(303, 206));
		((ViewableComponent) withName("Cell_key = 3 ,value = 1")).setPreferredLocation(new Point(38, 28));
	}
}
