package CAMod;

import java.awt.Dimension;
import java.awt.Point;
import java.util.Random;

import SimpArcMod.genr;
import javafx.application.Application;
import javafx.stage.Stage;
import model.modeling.CAModels.TwoDimCellSpace;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableComponentUtil;

public class GameOfLifeDeterministic extends TwoDimCellSpace {

	// A b-heptomino looks like this:
	// X
	// XXX
	// X XX
	// public static final int[][] b_heptomino = new int[][] { { 0, 1, 1 }, { 1, 1, 0 }, { 0, 1, 1 }, { 0, 0, 1 } };

	public GameOfLifeDeterministic() {
		this(4,3);

	}

	public GameOfLifeDeterministic(int xDim, int yDim) {
		super("Game of Life", xDim, yDim);

//		clock g = new clock("g", 1);
//		add(g);
		this.numCells = xDim * yDim;
		for (int i = 0; i < xDimCellspace; i++) {
			for (int j = 0; j < yDimCellspace; j++) {
				LifeDeterministic life = new LifeDeterministic(i, j);
				addCell(life);
				
				if ((i % 2) == 0 && (j % 1) == 0) 
					life.isLife = 1;
				else if ((i % 1) == 0 && (j % 2) == 0)
					life.isLife= 0;
				else if ((i % 1) == 0 && (j % 1) == 0)
					life.isLife= 1;
		
				//life.initialize();
				System.out.println("initial STATE for " + life.getClass().getName() + " in the GAME OF LIFE is set in constructor");
				
//				addCoupling(g, "out", life, "clock");
			}
		}
		
//		for(int x=0;x<b_heptomino.length;x++)
//            for(int y=0;y<b_heptomino[x].length;y++){
//            	Life l = (Life)(getCell(x+xDim/2-b_heptomino.length/2, y+yDim/2-b_heptomino[x].length/2));
//            			l.isLife = b_heptomino[x][y];
//            			l.initialize();
//            }
        
		

		// Do the couplings

		doNeighborToNeighborCoupling();
		
	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1122, 700);
        ((ViewableComponent)withName("Cell_key = 2 ,value = 2")).setPreferredLocation(new Point(551, 489));
        ((ViewableComponent)withName("Cell_key = 3 ,value = 1")).setPreferredLocation(new Point(828, 244));
        ((ViewableComponent)withName("Cell_key = 2 ,value = 1")).setPreferredLocation(new Point(549, 257));
        ((ViewableComponent)withName("Cell_key = 1 ,value = 2")).setPreferredLocation(new Point(262, 485));
        ((ViewableComponent)withName("Cell_key = 0 ,value = 2")).setPreferredLocation(new Point(-6, 486));
        ((ViewableComponent)withName("Cell_key = 0 ,value = 1")).setPreferredLocation(new Point(-3, 270));
        ((ViewableComponent)withName("Cell_key = 1 ,value = 1")).setPreferredLocation(new Point(276, 257));
        ((ViewableComponent)withName("Cell_key = 1 ,value = 0")).setPreferredLocation(new Point(265, 50));
        ((ViewableComponent)withName("Cell_key = 0 ,value = 0")).setPreferredLocation(new Point(-1, 49));
        ((ViewableComponent)withName("Cell_key = 2 ,value = 0")).setPreferredLocation(new Point(547, 54));
        ((ViewableComponent)withName("Cell_key = 3 ,value = 2")).setPreferredLocation(new Point(822, 481));
        ((ViewableComponent)withName("Cell_key = 3 ,value = 0")).setPreferredLocation(new Point(819, 52));
    }
}
